modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="cinematicscenes"
version="${file.jarVersion}"
displayName="CinematicScenes"
description='''A client-driven cinematic cutscene engine prototype for story servers.'''
[[dependencies.cinematicscenes]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.cinematicscenes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
