modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="rpgcharacter"
version="0.1.0"
displayName="RPG Character Foundation"
description='''Base architecture for age, height and genetics on a medieval Forge RPG server.'''

[[dependencies.rpgcharacter]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.rpgcharacter]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
