вселенная:
  стартовая_стабильность: 100
  автоснижение_процентов_каждые_сек: 300
  шаг_снижения: 2
  звезда:
    минимум_минут: 3
    максимум_минут: 10
  авто_разлом:
    минимум_сек: 480
    максимум_сек: 1080
  коллапс_чанков:
    интервал_часов: 9
    случайных_чанков: 3
    восстановление_сек: 180
разломы:
  включены: true
  малый:
    жизнь_сек: 600
  живой:
    шаг_перемещения_сек: 20
  великий:
    волна_мобов: 8
нестабильность:
  стадия1_минут: 20
  стадия2_минут: 40
arg:
  авто_интервал_мин: 30
  авто_интервал_макс: 120
миры:
  сломанный_оверворлд: fractured_broken_overworld
  кибер_измерение: fractured_cyber_dimension
  море_пустоты: fractured_void_sea
