name: LightBlockPlugin
version: 1.0.0
main: com.hazer.lightblock.LightBlockPlugin
api-version: '1.21'
author: Hazer_2_0
description: Добавляет крафт невидимых светоблоков через GUI с сохранением уровней.
commands:
  lightblock:
    description: Открыть GUI крафта светоблоков.
    usage: /lightblock
    aliases: [lb]
permissions:
  lightblock.use:
    description: Разрешает использовать /lightblock.
    default: true
